name: Running tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write  # Ensure write permission for contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Provision with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: AMLsim/amlsim.yml
          environment-name: amlsim
          cache-downloads: true

      - name: Run tests with pytest
        shell: bash -l {0}
        run: |
          set -e
          micromamba activate amlsim
          micromamba install pytest pytest-cov
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=amlsim amlsim/tests/ | tee pytest-coverage.txt
          cat ./pytest-coverage.txt
