name: Running tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Ruff Linting
        uses: chartboost/ruff-action@v1

  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write  # Ensure write permission for contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Provision with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: leakpro
          cache-downloads: true

      - name: Run tests with pytest
        shell: bash -l {0}
        run: |
          set -e
          micromamba activate leakpro
          micromamba install pytest pytest-cov
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=leakpro leakpro/tests/ | tee pytest-coverage.txt
          cat ./pytest-coverage.txt
