# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Running tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11
      - name: provision-with-micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: AMLsim/amlsim.yml
          environment-name: amlsim
          cache-downloads: true
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          micromamba activate amlsim
          micromamba install pytest pytest-cov
          python -m pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=scripts tests/ | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        if: github.event_name == 'pull_request'
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          title: Coverage Report
          badge-title: Overall Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          junitxml-path: ./pytest.xml
