name: Running tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write  # Ensure write permission for contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.14

      - name: Install dependencies from pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run tests with pytest
        shell: bash -l {0}
        working-directory: /sim/AMLsim
        run: |
          set -e
          pip install pytest pytest-cov coverage-badge
          export PYTHONPATH=$(pwd):$PYTHONPATH
          pytest --cov=amlsim --cov-report=term-missing:skip-covered --cov-report=xml --cov-report=html ./tests/
          cat ./coverage.xml
          
      - name: Create Coverage Badge
        run: |
          mkdir -p badges
          coverage-badge -o badges/coverage.svg -f
  
      - name: Deploy Coverage Badge to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: badges